### PR TITLE
added support for Finnish translations + Finnish localization

### PR DESCRIPTION
**Pull request by fergusq**

### CODE REVIEW

**Comment by De7vID** [comment]
I would normally leave a language in "beta" when first launching but Finnish is pretty complete. The only things which are missing are the entries in the `examples` and `extra` files. I would prefer if these are completed before removing the "beta".

Also, I need some time to test this, but also there is going to be a database update in December for the **qepHom'a'** 2020 vocabulary. I might release the vocab update together with Finnish depending on the timing.

**Comment by De7vID** [comment]
Actually, I think I'll release a new version of the app with Finnish support to the beta channel first, to test it independently of a data update. Then when Lieven releases the new vocab, I'll bundle that up and push it to production.

@fergusq Are you on the beta channel? You can join it in the app details page in the Play Store.

**Comment by fergusq** [comment]
Unfortunately, I don't have access to Google Play. I can test the application if you send me an APK.

**Comment by De7vID** [comment]
How are you downloading the app?

**Comment by fergusq** [comment]
I tried the version from F-droid but it didn't work so I had a friend send me the APK from their phone.

**Comment by De7vID** [comment]
Is your friend on the beta channel? I could send you the APK, but I I would prefer not to send APKs around to testers and just rely on the normal distribution mechanism.

I don't know why the version from F-Droid doesn't work. What do you mean by this? Did it fail to download? If you can open the app's info page, what version was it?

**Comment by fergusq** [comment]
The database seems to be empty in the F-droid version. There are no search results and not even the front page loads (it's just black). The version on the side bar is 2020.08.24a.

It seems that the app version is older, as there is an option for "Lessons (deprecated)" in the menu that is not present in the Google Play version I have.

**Comment by De7vID** [comment]
I've pushed release 2020.12.16b which has both Finnish support and the latest vocabulary from the Saarbrücken **qepHom'a'** 2020. I don't know the process by which the app gets updated or whatever on F-Droid, though.

**Comment by fergusq** [comment]
It seems that the new version you released only has English and German definitions, not Finnish, Portuguese, Swedish etc.

**Comment by De7vID** [comment]
Can you update the database (to 2020.12.16c) and try again? You can do this in the menu by first enabling "Unsupported features" under Preferences. Then a menu option named "Check for database update" should appear.

**Pull request merged**
